name: Runner check

on:
  workflow_dispatch:

jobs:
  check-runner:
    runs-on: [self-hosted, Linux, X64, homelab, deploy]

    steps:
      - name: Print runner info
        run: |
          hostname
          whoami
          pwd
          uname -a

      - name: Check Docker
        run: |
          docker --version
          docker compose version

      - name: Check app directory
        run: |
          test -d /srv/apps/OSK-Manager/deploy
          ls -la /srv/apps/OSK-Manager/deploy
